name: Coq Verification

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # Allow manual trigger

jobs:
  # ============================================
  # Job 1: Docker-based verification (pinned)
  # ============================================
  docker-verify:
    name: Docker Verify (Coq 8.18.0 pinned)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build Docker container
        run: docker build -t ucf-gutt-extensions:ci .
      
      - name: Show build manifest
        run: docker run --rm ucf-gutt-extensions:ci manifest
      
      - name: Run axiom audit
        run: |
          COUNT=$(docker run --rm ucf-gutt-extensions:ci audit 2>&1 | grep -E "^[0-9]+" | head -1)
          echo "Exports verified: $COUNT"
          if [ "$COUNT" != "163" ]; then
            echo "❌ AUDIT FAILED: Expected 163, got $COUNT"
            exit 1
          fi
          echo "✅ AUDIT PASSED: 163/163 exports closed under global context"
      
      - name: Verify checksums
        run: docker run --rm ucf-gutt-extensions:ci checksums

  # ============================================
  # Job 2: Native Coq build (matrix)
  # ============================================
  native-build:
    name: Native Build (Coq ${{ matrix.coq-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq-version: ['8.18', '8.19']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Coq
        uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq-version }}
          ocaml_version: default
          custom_script: |
            echo "::group::Build library"
            make build
            echo "::endgroup::"
            
            echo "::group::Run coqchk"
            make check
            echo "::endgroup::"
            
            echo "::group::Axiom audit"
            make audit
            echo "::endgroup::"

  # ============================================
  # Job 3: Verification summary
  # ============================================
  summary:
    name: Verification Summary
    runs-on: ubuntu-latest
    needs: [docker-verify, native-build]
    if: always()
    
    steps:
      - name: Check results
        run: |
          echo "╔════════════════════════════════════════════════════════════════╗"
          echo "║              UCF/GUTT Extensions CI Summary                    ║"
          echo "╠════════════════════════════════════════════════════════════════╣"
          echo "║  Docker (pinned):  ${{ needs.docker-verify.result }}"
          echo "║  Native (matrix):  ${{ needs.native-build.result }}"
          echo "╚════════════════════════════════════════════════════════════════╝"
          
          if [ "${{ needs.docker-verify.result }}" != "success" ]; then
            echo "❌ Docker verification failed"
            exit 1
          fi
          
          if [ "${{ needs.native-build.result }}" != "success" ]; then
            echo "❌ Native build failed"
            exit 1
          fi
          
          echo ""
          echo "✅ ALL VERIFICATIONS PASSED"
          echo "   • 163 exports audited"
          echo "   • 0 axioms"
          echo "   • coqchk verified"
